### ISSUE TITLE
Load host data to data.gov for dashboard.

### ISSUE THREAD

**Issue by nokout** [AusDTO/discoCrawl#12]

**Comment by monkeypants** [comment]
is this "on a periodic schedule, update a data set in data.gov.au with the result of a query against WebDocument"?

If so, it might be good to do it as a scheduled job in discoveryLayer/crawler/tasks.py rather than discoCrawl/. We already have scheduled jobs there that do other stuff with queries against WebDocument, and it might be nice to try out the data.gov.au API.

**Comment by nokout** [comment]
Pretty much. This is the one we spoke about this morning where we need to integrate some whitelist/blacklist assertions. Its half done now. Lets talk about it again tomorrow though. In the end it does belong in the dicoveryLayer but we need to make an interim solution.

**Comment by nokout** [comment]
Data is now loading
